### ISSUE TITLE
configure script uses bad sed escaping

### ISSUE THREAD

**Issue by chneukirchen** [Daniel-Diaz/pcre-light#2]
pcre-light-0.4.0.3 uses this inside the configure script:
```
    sed 's,@CPPFLAGS@,'"$CPPFLAGS"',g;s,@LDFLAGS@,'"$LDFLAGS"',g'  \
        < pcre-light.buildinfo.in > pcre-light.buildinfo
```
However, `,` can appear in LDFLAGS, e.g. as `-Wl,-z,relro` or similar, breaking the sed command.
Perhaps `#` or `!` would be safer to use, or the escape char should be escaped in the replacement.

**Comment by mitchty** [comment]
I hit this problem with busybox sed on alpine linux trying to compile the latest stack:

```
Found CPPFLAGS in environment: '-Os -fomit-frame-pointer'
sed: bad option in substitution expression
sh returned ExitFailure 1
```
Switching to #'s fixes things:
```
--- configure
+++ configure.original
@@ -4,6 +4,6 @@
 # subst standard header path variables
 if test -n "$CPPFLAGS" ; then
     echo "Found CPPFLAGS in environment: '$CPPFLAGS'"
-    sed 's#@CPPFLAGS@#'"$CPPFLAGS"'#g;s#@LDFLAGS@#'"$LDFLAGS"'#g'  \
+    sed 's,@CPPFLAGS@,'"$CPPFLAGS"',g;s,@LDFLAGS@,'"$LDFLAGS"',g'  \
         < pcre-light.buildinfo.in > pcre-light.buildinfo
 fi
```

Shall I submit a pull request?

**Comment by Daniel-Diaz** [comment]
@mitchty Feel free to submit it. I will review it as soon as I can.

Thanks @chneukirchen for reporting the issue.

:+1:
