### ISSUE TITLE
Matching empty ByteString fails

### ISSUE THREAD

**Issue by mitchellwrosen** [Daniel-Diaz/pcre-light#6]
Hi, is this a bug? Matching `".*"` against `Data.ByteString.empty` fails:

```haskell
> match (compile ".*" []) Data.ByteString.empty []
Nothing
```

Weirdly, it works when matching against an empty bytestring constructed with a string literal:

```haskell
> match (compile ".*" []) "" []
Just [""]
```

**Comment by netom** [comment]
This is also an issue when reading files and chopping them up with ByteString.lines, since empty lines will also be represented the sames as ByteString.empty. I'd be happy to see this PR merged as my project "codestats" makes heavy use of this library.
